### ISSUE TITLE
TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType

### ISSUE THREAD

**Issue by kiblik** [dunbarcyber/cyphon#166]
Hi,
I tried run `python3 ./cyphon/receiver/receiver.py watchdogs 4` but it crashed after read message from RabbitMQ

```
ERROR An error occurred while processing the message '{"sequence":0,"@timestamp":"2017-08-07T11:06:29.216Z","@version":"1","host":"m01","message":"some message","type":"my type"}':
  get_by_natural_key() argument after * must be an iterable, not NoneType
Traceback (most recent call last):
  File "./cyphon/receiver/receiver.py", line 120, in process_msg
    consumer_func(doc_obj)
  File "xxx/cyphon/cyphon/transaction.py", line 97, in _decorator
    result = func(*args, **kwargs)
  File "xxx/cyphon/alarms/models.py", line 70, in process
    alarms = self.find_relevant(doc_obj.distillery)
  File "/usr/local/lib/python3.5/dist-packages/Django-1.11.3-py3.5.egg/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "xxx/cyphon/cyphon/documents.py", line 108, in distillery
    return distillery_model.objects.get_by_natural_key(*natural_key)
TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType
```

Can you help me?
Thanks

**Comment by kiblik** [comment]
I found problem. I forget this lines:
```
    mutate {
        add_field => {
            "collection" => "elasticsearch.cyphon.%{type}"
        }
    }
```
