### ISSUE TITLE
Chromedriver?

### ISSUE THREAD

**Issue by DigiAngel** [dunbarcyber/cyphon#20]
Trying this in a test environment and this is what I see:
~~~
======================================================================
ERROR: setUpClass (sifter.mailsifter.mailcondensers.tests.test_functional.ChangeMailCondenserConfigToolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 170, in setUpClass
    cls.driver = get_web_driver(cls.__name__)
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 131, in get_web_driver
    return _get_local_driver(browser)
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 111, in _get_local_driver
    return Chrome()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


----------------------------------------------------------------------
Ran 1060 tests in 118.034s
~~~
Is there something I need to do on my end to fix this?  Thank you.

**Comment by lhadjchikh** [comment]
Sorry, we just upgraded from Selenium 2 to Selenium 3, and I'm trying to sort out issues with locating web drivers. We are currently relying on SauceLabs to run our functional tests in Travis CI. I'm reworking them to run using a Selenium container in Cyphondock for local testing, but it's still a work in progress.

Until this is worked out, you can disable functional tests by setting the environment variable `FUNCTIONAL_TESTS_ENABLED` to `False`, or by changing the setting in your `cyphon/settings/conf.py` file. That will skip these tests and the error should go away.

I've had trouble using Boolean values in Docker Compose files, so if you set the environment variable there, you may need to set it as the string "False" (in quotation marks).

**Comment by DigiAngel** [comment]
Thanks...I'll give this a shot on Monday and report here.

**Comment by DigiAngel** [comment]
Thanks....functional tests are disabled, but still the same error :(
~~~
Functional tests are disabled, so those tests will be skipped.
Cannot connect to MongoDB. MongoDB tests will be skipped.
Twitter authentication credentials are missing, so Twitter API tests will be skipped.
...<snip>...............
======================================================================
ERROR: setUpClass (bottler.bottles.tests.test_functional.BottleFunctionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 170, in setUpClass
    cls.driver = get_web_driver(cls.__name__)
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 131, in get_web_driver
    return _get_local_driver(browser)
  File "/usr/src/app/cyphon/tests/functional_tests.py", line 111, in _get_local_driver
    return Chrome()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
~~~

**Comment by DigiAngel** [comment]
In any case I believe it still starts, so that's a plus.

**Comment by lhadjchikh** [comment]
Okay, thanks for trying! I think I just need to catch this exception when the webdriver is not on your local PATH. In the meantime, just ignore these errors. :-) The functional tests aren't mission critical; they just test some aspects of the admin interface in a web browser (filtering choices, etc.). Thanks for reporting this issue, though; I will work on a patch. And please let us know if you encounter any others problems!

**Comment by DigiAngel** [comment]
Will do thanks.....truth be told I'm struggling to get this to fly...I'll gather up all my challenges and post a ticket in...the cyphondock repo as it applies to both.  Thanks again.

**Comment by lhadjchikh** [comment]
That would be fantastic, thanks! I'm working on some fixes for Cyphondock right now, but I haven't merged them to the master branch yet. Definitely let me know what problems you're encountering and I'll get on them ASAP.
