### ISSUE TITLE
No mapping found for [_saved_date] in order to sort on

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphon#365]
I recently upgraded from 1.4 to 1.6 and having some issues. I had previously setup and had functioning a distillery that was getting alerts from Nessus data. Once I upgraded I noticed this traceback from tailing the celeryworker:

```
[2018-01-23 19:20:05,184: ERROR/ForkPoolWorker-4] Task tasks.run_health_check[0d0d5839-0967-4f7c-bd5a-d88e5a467dbd] raised unexpected: RequestError(400, 'search_phase_execution_exception', {'error': {'root_cause': [{'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'WY9JtQHeT9GLByHb3UJadQ', 'index': 'wazuh-2017-09-25'}, {'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'o8KBmn5ITCqkDh3AqGdiOg', 'index': 'wazuh-2017-09-26'}, {'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'd5u6S3xJTcqasla4Xk2lUQ', 'index': 'wazuh-2017-09-27'}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'wazuh-2017-09-25', 'node': 'YbjtnJ01RKu1GCed09phdQ', 'reason': {'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'WY9JtQHeT9GLByHb3UJadQ', 'index': 'wazuh-2017-09-25'}}, {'shard': 0, 'index': 'wazuh-2017-09-26', 'node': 'YbjtnJ01RKu1GCed09phdQ', 'reason': {'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'o8KBmn5ITCqkDh3AqGdiOg', 'index': 'wazuh-2017-09-26'}}, {'shard': 0, 'index': 'wazuh-2017-09-27', 'node': 'YbjtnJ01RKu1GCed09phdQ', 'reason': {'type': 'query_shard_exception', 'reason': 'No mapping found for [_saved_date] in order to sort on', 'index_uuid': 'd5u6S3xJTcqasla4Xk2lUQ', 'index': 'wazuh-2017-09-27'}}]}, 'status': 400})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/cyphon/cyphon/tasks.py", line 59, in run_health_check
    monitor.update_status()
  File "/usr/src/app/cyphon/monitors/models.py", line 407, in update_status
    self.save()  # update monitor
  File "/usr/src/app/cyphon/monitors/models.py", line 177, in save
    self._update_fields()
  File "/usr/src/app/cyphon/monitors/models.py", line 379, in _update_fields
    self._update_doc_info()
  File "/usr/src/app/cyphon/monitors/models.py", line 292, in _update_doc_info
    doc = self._get_most_recent_doc(distillery)
  File "/usr/src/app/cyphon/monitors/models.py", line 282, in _get_most_recent_doc
    results = distillery.find(query, sorter, page=1, page_size=1)
  File "/usr/src/app/cyphon/distilleries/models.py", line 410, in find
    return self.collection.find(query, sorter, page, page_size)
  File "/usr/src/app/cyphon/warehouses/models.py", line 491, in find
    return self.engine.find(query, sorter, page, page_size)
  File "/usr/src/app/cyphon/engines/elasticsearch/engine.py", line 108, in _decorator
    return func(*args, **kwargs)
  File "/usr/src/app/cyphon/engines/elasticsearch/engine.py", line 141, in _call
    return func(*args, **kwargs)
  File "/usr/src/app/cyphon/engines/elasticsearch/engine.py", line 457, in find
    offset=offset
  File "/usr/src/app/cyphon/engines/elasticsearch/engine.py", line 388, in _get_search_results
    return ELASTICSEARCH.search(**params)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'No mapping found for [_saved_date] in order to sort on')
```

I can also recreate this when trying to update a monitor (assuming that calls `.update_status()`). Sure enough, when I check out the data in ES using Kibana I can see that field doesn't exist on my Nessus data (I have it going into a separate index from logstash). Does the index need to get recreated, or is this something I can do update out-of-band? I'm assuming for some reason during the upgrade process this did not carry over in ES

**Comment by lhadjchikh** [comment]
Ah, I think it's looking for the `_saved_date` field that Cyphon adds when it's saving data, but if the data is going directly to ES, the field won't get added. Can you double check the Distillery and make sure "is_shell" is checked? That should tell Cyphon that the `_saved_date` field doesn't exist. Then make sure you have a date field selected in the Taste associated with the Distillery's Container. This could be a `@timestamp` field, for example, or whatever date field you're parsing out from the messages.

**Comment by adamstauffer** [comment]
I changed the distillery to "is_shell" and restarted everything. also, my container is uing the `@timestamp` field for the date in the taste so it should be good there. when I ran some scans again to get data into ES, the field still doesn't show up. is that change supposed to add the field to newly indexed data?

**Comment by lhadjchikh** [comment]
Sorry, which field do mean, `@timestamp`? Logstash adds that field when it saves documents to Elasticsearch. If you don't see that field in Kibana, you'll need to select whatever date field is included with the scan, and add that to the Bottle used by your Container.

**Comment by adamstauffer** [comment]
no sorry, `_saved_date` is still missing

**Comment by lhadjchikh** [comment]
Oh, yeah, that won't be added unless Cyphon is saving the data (rather than Logstash, for instance).

**Comment by adamstauffer** [comment]
ok so had to change all distilleries i had previously configured in 1.4 (and were working) to use `is_shell`. no clue how this worked before but im getting data reliably now. thanks

**Comment by lhadjchikh** [comment]
It's because Monitors now search the database to update their status. Before, you had to send a copy of the data to Cyphon so the Monitors could examine it. This didn't require use of a date field because the Monitors could fall back to the current time (when they received the data).
