### ISSUE TITLE
twitter tasks constantly crashing

### ISSUE THREAD

**Issue by adamstauffer** [dunbarcyber/cyphon#392]
ive been noticing that twitter data has stopped coming in for me every few days. after finally restarting the celeryworkers with debug level logging (which should have been easier) im seeing these tracebacks:

```
[2018-02-09 18:14:40,749: ERROR/ForkPoolWorker-2] An error occurred with the Twitter stream: 'NoneType' object has no attribute 'strip'
[2018-02-09 18:14:40,751: WARNING/ForkPoolWorker-2] Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/cyphon/aggregator/pumproom/streamcontroller.py", line 61, in _run_faucet
    self.faucet.start(self.query)
  File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
    result = func(*args, **kwargs)
  File "/usr/src/app/cyphon/ambassador/transport.py", line 321, in start
    self.cargo = self.process_request(obj)
  File "/usr/src/app/cyphon/platforms/twitter/handlers.py", line 322, in process_request
    stream.filter(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python3.6/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python3.6/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/usr/local/lib/python3.6/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python3.6/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

this looks to be a [common issue with the tweepy package](https://github.com/tweepy/tweepy/issues?utf8=%E2%9C%93&q=NoneType+has+no+attribute) and there are a few outstanding PRs to fix too.

normally you would expect that if bad data is encountered in twitter by the celery task, it would fail and move on. however, this doesnt seem to be the case for me. i can see with the debug logs still enabled that the `run_bkgd_search` tasks still run, but "succeed" very quickly. these tasks do not find data and insert it into ES:

```
[2018-02-09 18:53:24,265: INFO/MainProcess] Received task: tasks.run_bkgd_search[f4e9b578-6fc7-419d-b9ee-c4d097b788f7]
[2018-02-09 18:53:24,265: DEBUG/MainProcess] TaskPool: Apply <function _fast_trace_task at 0x7f37d402be18> (args:('tasks.run_bkgd_search', 'f4e9b578-6fc7-419d-b9ee-c4d097b788f7', {'lang': 'py', 'task': 'tasks.run_bkgd_search', 'id': 'f4e9b578-6fc7-419d-b9ee-c4d097b788f7', 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f4e9b578-6fc7-419d-b9ee-c4d097b788f7', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen24@d53923320a5d', 'reply_to': 'b81c81de-e5e1-346e-9ca9-ce6d1dc11970', 'correlation_id': 'f4e9b578-6fc7-419d-b9ee-c4d097b788f7', 'delivery_info': {'exchange': '', 'routing_key': 'celery', 'priority': 0, 'redelivered': False}}, '[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]', 'application/json', 'utf-8') kwargs:{})
[2018-02-09 18:53:24,274: DEBUG/MainProcess] Task accepted: tasks.run_bkgd_search[f4e9b578-6fc7-419d-b9ee-c4d097b788f7] pid:40
[2018-02-09 18:53:24,439: INFO/ForkPoolWorker-4] Task tasks.run_bkgd_search[f4e9b578-6fc7-419d-b9ee-c4d097b788f7] succeeded in 0.17322726361453533s: None
```

**Comment by adamstauffer** [comment]
after reading through the code, any exception encountered from [here](https://github.com/dunbarcyber/cyphon/blob/master/cyphon/aggregator/pumproom/streamcontroller.py#L61) will not clean up the lock properly on the Stream. this includes if you're running on AWS and you experience random network failures preventing you from hitting the Twitter API while the task is running. my only solution for now is a blind except on the call to `self.faucet.start()` which isn't the best solution but ensures things get cleaned up for subsequent tasks to run
