### ISSUE TITLE
Email Alerts Issue.

### ISSUE THREAD

**Issue by p3nreel** [dunbarcyber/cyphon#590]
Hello, I have installed Cyphon via docker and went through the tutorial (step by step) on "Generating Alerts from Email", however email alerts are not being triggered at the console. I ran the command (docker logs -f cyphondock_celeryworker_1) and received the errors below. Any help would be greatly appreciated. Thanks!

PermissionError: [Errno 13] Permission denied: '/usr/src/app/media/mailbox_attachments/2018/06/26'
[2018-06-26 18:09:32,623: ERROR/ForkPoolWorker-2] Task tasks.get_new_mail[78468cac-fcfe-4450-9d52-203c4f8b1f00] raised unexpected: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/cyphon/cyphon/tasks.py", line 45, in get_new_mail
    mailbox.get_new_mail()
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 413, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 230, in process_incoming_message
    msg = self._process_message(message)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 368, in _process_message
    message = self._get_dehydrated_message(message, msg)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 258, in _get_dehydrated_message
    self._get_dehydrated_message(part, record)
  File "/usr/local/lib/python3.6/site-packages/django_mailbox/models.py", line 298, in _get_dehydrated_message
    msg.get_payload(decode=True)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 321, in _save
    os.makedirs(directory)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/src/app/media/mailbox_attachments/2018/06/26'
[2018-06-26 18:18:34,479: ERROR/ForkPoolWorker-5] Default MailMunger "default" is not configured.
[2018-06-26 18:31:29,816: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbit:5672/cyphon: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

**Comment by lhadjchikh** [comment]
The `media` volume on the host that's being used by the Docker container has to be writable by cyphon (it's mapped to the `/usr/src/app/media` directory inside the container). This is a recurring permissions issue that I still haven't figured out, because it's supposed to be set correctly by the Dockerfile. But I think you can just change the permissions yourself, either on the host or from inside the container. To do this from inside the cyphon container, you can give this a try:
```
sudo docker exec -it cyphondock_cyphon_1 sh -c "chown -R cyphon:cyphon /usr/src/app/media && chmod -R 775 /usr/src/app/media"
```

**Comment by p3nreel** [comment]
Thank you lhadjchikh for the quick response. Looks like that did the trick. I will close this issue.
