### ISSUE TITLE
Errors processing log messages in watchdog consumer cascade

### ISSUE THREAD

**Issue by darvid** [dunbarcyber/cyphon#77]
I probably configured something incorrectly, but I'm currently running into the following errors continuously in a container running the watchdogs:

```watchdogs_1      | TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | ERROR An error occurred while processing the message '{"ver":"1","@uuid":"78779192-6bb0-48aa-88e8-ab4faeb2b9a5","pid":"13148","type":"logspout","tags":["multiline"],"@message":"ERROR An error occurred while processing the message '{\"ver\":\"1\",\"@uuid\":\"3a4d5ad9-00f8-4ac7-b7f2-94bc707acc18\",\"pid\":\"13148\",\"type\":\"logspout\",\"tags\":[\"multiline\"],\"@message\":\"    result = func(*args, **kwargs)\\nTraceback (most recent call last):\\n  File \\\"/usr/src/app/cyphon/alarms/models.py\\\", line 70, in process\\n    alarms = self.find_relevant(doc_obj.distillery)\\n  File \\\"/usr/local/lib/python3.6/site-packages/django/utils/functional.py\\\", line 35, in __get__\\n  File \\\"/usr/src/app/cyphon/cyphon/documents.py\\\", line 108, in distillery\\n    res = instance.__dict__[self.name] = self.func(instance)\\n    return distillery_model.objects.get_by_natural_key(*natural_key)\\nTypeError: get_by_natural_key() argument after * must be an iterable, not NoneType\",\"@timestamp\":\"2017-05-30T19:57:26.000Z\",\"container_name\":\"cyphondock_watchdogs_1\",\"syslog5424_pri\":\"11\",\"@version\":\"1\",\"host\":\"172.18.0.16\",\"container_id\":\"9e16b937b644\"}':\n  get_by_natural_key() argument after * must be an iterable, not NoneType","@timestamp":"2017-05-30T19:57:26.000Z","container_name":"cyphondock_watchdogs_1","syslog5424_pri":"11","@version":"1","host":"172.18.0.16","container_id":"9e16b937b644"}':
watchdogs_1      |   get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | Traceback (most recent call last):
watchdogs_1      |   File "receiver/receiver.py", line 103, in process_msg
watchdogs_1      |     consumer_func(doc_obj)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
watchdogs_1      |     result = func(*args, **kwargs)
watchdogs_1      |   File "/usr/src/app/cyphon/alarms/models.py", line 70, in process
watchdogs_1      |     alarms = self.find_relevant(doc_obj.distillery)
watchdogs_1      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
watchdogs_1      |     res = instance.__dict__[self.name] = self.func(instance)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/documents.py", line 108, in distillery
watchdogs_1      |     return distillery_model.objects.get_by_natural_key(*natural_key)
watchdogs_1      | TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | ERROR An error occurred while processing the message '{"ver":"1","@uuid":"5a48dd06-d219-4245-b7c0-34af65ea693c","pid":"13148","type":"logspout","tags":["multiline"],"@message":"Traceback (most recent call last):\n  File \"receiver/receiver.py\", line 103, in process_msg\n    consumer_func(doc_obj)\n  File \"/usr/src/app/cyphon/cyphon/transaction.py\", line 97, in _decorator\n    result = func(*args, **kwargs)\n  File \"/usr/src/app/cyphon/alarms/models.py\", line 70, in process\n    alarms = self.find_relevant(doc_obj.distillery)\n  File \"/usr/local/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/usr/src/app/cyphon/cyphon/documents.py\", line 108, in distillery\n    return distillery_model.objects.get_by_natural_key(*natural_key)\nTypeError: get_by_natural_key() argument after * must be an iterable, not NoneType","@timestamp":"2017-05-30T19:57:26.000Z","container_name":"cyphondock_watchdogs_1","syslog5424_pri":"11","@version":"1","host":"172.18.0.16","container_id":"9e16b937b644"}':
watchdogs_1      |   get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | Traceback (most recent call last):
watchdogs_1      |   File "receiver/receiver.py", line 103, in process_msg
watchdogs_1      |     consumer_func(doc_obj)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
watchdogs_1      |     result = func(*args, **kwargs)
watchdogs_1      |   File "/usr/src/app/cyphon/alarms/models.py", line 70, in process
watchdogs_1      |     alarms = self.find_relevant(doc_obj.distillery)
watchdogs_1      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
watchdogs_1      |     res = instance.__dict__[self.name] = self.func(instance)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/documents.py", line 108, in distillery
watchdogs_1      |     return distillery_model.objects.get_by_natural_key(*natural_key)
watchdogs_1      | TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | ERROR An error occurred while processing the message '{"ver":"1","@uuid":"bca86b92-faa5-4dc1-ad49-8369a3325088","pid":"13148","type":"logspout","tags":["multiline"],"@message":"ERROR An error occurred while processing the message '{\"ver\":\"1\",\"@uuid\":\"2231eb40-e5c8-46bb-bfe6-f3f4bbc7454f\",\"pid\":\"13148\",\"type\":\"logspout\",\"tags\":[\"multiline\"],\"@message\":\"ERROR An error occurred while processing the message '{\\\"ver\\\":\\\"1\\\",\\\"@uuid\\\":\\\"27e571dc-c240-4b5e-aef2-97f523bf038d\\\",\\\"pid\\\":\\\"13148\\\",\\\"type\\\":\\\"logspout\\\",\\\"tags\\\":[\\\"multiline\\\"],\\\"@message\\\":\\\"ERROR An error occurred while processing the message '{\\\\\\\"ver\\\\\\\":\\\\\\\"1\\\\\\\",\\\\\\\"@uuid\\\\\\\":\\\\\\\"87410104-70de-48b6-9cc0-f752dfdcaa8e\\\\\\\",\\\\\\\"pid\\\\\\\":\\\\\\\"13148\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"logspout\\\\\\\",\\\\\\\"tags\\\\\\\":[\\\\\\\"multiline\\\\\\\"],\\\\\\\"@message\\\\\\\":\\\\\\\"Traceback (most recent call last):\\\\\\\\n  File \\\\\\\\\\\\\\\"/usr/src/app/cyphon/cyphon/transaction.py\\\\\\\\\\\\\\\", line 97, in _decorator\\\\\\\\n  File \\\\\\\\\\\\\\\"/usr/src/app/cyphon/alarms/models.py\\\\\\\\\\\\\\\", line 70, in process\\\\\\\\n    result = func(*args, **kwargs)\\\\\\\\n  File \\\\\\\\\\\\\\\"/usr/local/lib/python3.6/site-packages/django/utils/functional.py\\\\\\\\\\\\\\\", line 35, in __get__\\\\\\\\n    res = instance.__dict__[self.name] = self.func(instance)\\\\\\\\n  File \\\\\\\\\\\\\\\"/usr/src/app/cyphon/cyphon/documents.py\\\\\\\\\\\\\\\", line 108, in distillery\\\\\\\\n    return distillery_model.objects.get_by_natural_key(*natural_key)\\\\\\\\nTypeError: get_by_natural_key() argument after * must be an iterable, not NoneType\\\\\\\\n    alarms = self.find_relevant(doc_obj.distillery)\\\\\\\\n  get_by_natural_key() argument after * must be an iterable, not NoneType\\\\\\\",\\\\\\\"@timestamp\\\\\\\":\\\\\\\"2017-05-30T19:57:25.000Z\\\\\\\",\\\\\\\"container_name\\\\\\\":\\\\\\\"cyphondock_watchdogs_1\\\\\\\",\\\\\\\"syslog5424_pri\\\\\\\":\\\\\\\"11\\\\\\\",\\\\\\\"@version\\\\\\\":\\\\\\\"1\\\\\\\",\\\\\\\"host\\\\\\\":\\\\\\\"172.18.0.16\\\\\\\",\\\\\\\"container_id\\\\\\\":\\\\\\\"9e16b937b644\\\\\\\"}':\\\\n  get_by_natural_key() argument after * must be an iterable, not NoneType\\\",\\\"@timestamp\\\":\\\"2017-05-30T19:57:25.000Z\\\",\\\"container_name\\\":\\\"cyphondock_watchdogs_1\\\",\\\"syslog5424_pri\\\":\\\"11\\\",\\\"@version\\\":\\\"1\\\",\\\"host\\\":\\\"172.18.0.16\\\",\\\"container_id\\\":\\\"9e16b937b644\\\"}':\\n  File \\\"receiver/receiver.py\\\", line 103, in process_msg\",\"@timestamp\":\"2017-05-30T19:57:26.000Z\",\"container_name\":\"cyphondock_watchdogs_1\",\"syslog5424_pri\":\"11\",\"@version\":\"1\",\"host\":\"172.18.0.16\",\"container_id\":\"9e16b937b644\"}':\n  get_by_natural_key() argument after * must be an iterable, not NoneType","@timestamp":"2017-05-30T19:57:26.000Z","container_name":"cyphondock_watchdogs_1","syslog5424_pri":"11","@version":"1","host":"172.18.0.16","container_id":"9e16b937b644"}':
watchdogs_1      |   get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | Traceback (most recent call last):
watchdogs_1      |   File "receiver/receiver.py", line 103, in process_msg
watchdogs_1      |     consumer_func(doc_obj)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
watchdogs_1      |     result = func(*args, **kwargs)
watchdogs_1      |   File "/usr/src/app/cyphon/alarms/models.py", line 70, in process
watchdogs_1      |     alarms = self.find_relevant(doc_obj.distillery)
watchdogs_1      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
watchdogs_1      |     res = instance.__dict__[self.name] = self.func(instance)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/documents.py", line 108, in distillery
watchdogs_1      |     return distillery_model.objects.get_by_natural_key(*natural_key)
watchdogs_1      | TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | ERROR An error occurred while processing the message '{"ver":"1","@uuid":"b10d05e6-eaf1-4d79-acf6-5de10ab53275","pid":"13148","type":"logspout","tags":["multiline"],"@message":"Traceback (most recent call last):\n  File \"receiver/receiver.py\", line 103, in process_msg\n    consumer_func(doc_obj)\n  File \"/usr/src/app/cyphon/cyphon/transaction.py\", line 97, in _decorator\n    result = func(*args, **kwargs)\n  File \"/usr/src/app/cyphon/alarms/models.py\", line 70, in process\n    alarms = self.find_relevant(doc_obj.distillery)\n  File \"/usr/local/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/usr/src/app/cyphon/cyphon/documents.py\", line 108, in distillery\n    return distillery_model.objects.get_by_natural_key(*natural_key)\nTypeError: get_by_natural_key() argument after * must be an iterable, not NoneType","@timestamp":"2017-05-30T19:57:26.000Z","container_name":"cyphondock_watchdogs_1","syslog5424_pri":"11","@version":"1","host":"172.18.0.16","container_id":"9e16b937b644"}':
watchdogs_1      |   get_by_natural_key() argument after * must be an iterable, not NoneType
watchdogs_1      | Traceback (most recent call last):
watchdogs_1      |   File "receiver/receiver.py", line 103, in process_msg
watchdogs_1      |     consumer_func(doc_obj)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/transaction.py", line 97, in _decorator
watchdogs_1      |     result = func(*args, **kwargs)
watchdogs_1      |   File "/usr/src/app/cyphon/alarms/models.py", line 70, in process
watchdogs_1      |     alarms = self.find_relevant(doc_obj.distillery)
watchdogs_1      |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
watchdogs_1      |     res = instance.__dict__[self.name] = self.func(instance)
watchdogs_1      |   File "/usr/src/app/cyphon/cyphon/documents.py", line 108, in distillery
watchdogs_1      |     return distillery_model.objects.get_by_natural_key(*natural_key)
watchdogs_1      | TypeError: get_by_natural_key() argument after * must be an iterable, not NoneType

```

I believe somewhere along the line I had all logspout messages going directly to rabbit, and something else misconfigured that resulted in the original failure. But the failure itself gets logged and then replayed back, it seems like.

**Comment by lhadjchikh** [comment]
This is caused by messages from Logspout that aren't being processed properly by Cyphon because they don't have the `collection` field.

Cyphon needs the `collection` field to find the Distillery with which the document is associated. However, [config/logstash/pipeline/2-filter5-cyphon.conf](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/2-filter5-cyphon.conf#L9) only adds the `collection` field to log messages that aren't from Logspout (on the assumption that we don't want to forward container logs to Cyphon).

To make the errors go away, be sure that you don't forward these Logspout messages to RabbitMQ/Cyphon in [config/logstash/pipeline/3-output](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/logstash/pipeline/3-output.conf#L63) (or, alternatively, make sure you add the `collection` field to whatever messages you forward to RabbitMQ/Cyphon!).

**Comment by darvid** [comment]
Ahh, makes sense. Thank you!
